### ISSUE TITLE
Пустой репост, который ничего не показывает

### ISSUE THREAD

**Issue by Experience1-1** [openvk/mobile-android-legacy#10]
сам не до конца понимаю что это может быть
2-й скрин - комменты к этому посту (их нету, это не баг)
![Screenshot_20221019-194210_OpenVK](https://user-images.githubusercontent.com/104792484/196740647-589339e1-0af4-4f17-9e88-c0342d0181a5.png)
![Screenshot_20221019-194449_OpenVK](https://user-images.githubusercontent.com/104792484/196740676-3cf6c994-b570-473d-a10c-921213646260.png)

**Comment by tretdm** [comment]
ах да, забыл про картинки в репостах. это будет реализовано позже

**Comment by tretdm** [comment]
![изображение](https://user-images.githubusercontent.com/76806170/196744138-8c305466-b3a8-4b72-94fb-5cef9429d0c0.png)
кажись я понял в чем проблема

**Comment by tretdm** [comment]
@tretdm ой я нетуда

**Comment by Experience1-1** [comment]
+ полоса разделения на 2-м скрине под кнопками, а на 1-м -- над ними

**Comment by tretdm** [comment]
добавил поддержку картинок в коммите [bfa47e7](https://github.com/openvk/mobile-android-legacy/commit/bfa47e7dfa704599a7b29134d622dec37e4018fa)
а что насчет рекурсивных постов, пока неизвестно

**Comment by tretdm** [comment]
Проблему с ID оригинальных авторов можно считать полностью решённой в коммите [`8d9a6dc`](https://github.com/openvk/mobile-android-legacy/commit/8d9a6dce1fe356a439e3f763f83e8ae2f925a7bb).

**Comment by tretdm** [comment]
Уже неактуально, поскольку все поддерживаемые вложения из API должны работать и в репортах.

Посмотрите issue в движке OpenVK: https://github.com/openvk/openvk/issues/1056
