### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [openvk/mobile-android-legacy#102]
https://monitor.f-droid.org/builds/log/uk.openvk.android.legacy/176#site-footer

An aar file is added. What should we do?

**Comment by tretdm** [comment]
Import this aar-file to Gradle project, because using [FFmpegMediaPlayer 1.0.4](https://github.com/wseemann/FFmpegMediaPlayer) lib for decoding video from HTTP/HTTPS streams.

**Comment by linsui** [comment]
F-Droid doesn't allow binary dependency. It need to be pull from a trusted maven repo, e.g. maven central, or built from source. Is it available in a maven repo?

**Comment by tretdm** [comment]
Nope, available only 1.0.5 linked with AndroidX in repos

**Comment by tretdm** [comment]
Migrating an application to AndroidX may result in incompatibility with Android 2.x. Therefore, I did not use a more recent version, but decided to use the version that is currently not available in the libraries repositories.

**Comment by linsui** [comment]
Which version is used? The readme says 1.0.1 is used but you said that 1.0.4 is used.

**Comment by tretdm** [comment]
AARs from https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.4

**Comment by tretdm** [comment]
![screenshot](https://user-images.githubusercontent.com/76806170/221413478-2639f207-08d5-4908-8261-b9265084acba.png)

Wait, I haven't checked version 1.0.4 for availability. Initially, when I tried 1.0.1, it was not in the repository. I'm sorry.
[Try build again](https://github.com/openvk/mobile-android-legacy/commit/5f04d49e84643d3967be016e9da5933bd6cf4788).

**Comment by linsui** [comment]
Ah, that's great. Then I don't need to build it from source. What are those files in captures?

**Comment by tretdm** [comment]
@linsui Please build the APKs from new versions in a special `fdroid` variant.

**Comment by linsui** [comment]
The latest version builds. https://gitlab.com/fdroid/fdroiddata/-/commit/9be4d20b64e70a7ea15ef1876598303d60d7eb98 Is there anything needed to be changed?

**Comment by tretdm** [comment]
Nothing, only build variant
