### ISSUE TITLE
Верхняя панель с меню частично обрубает отображаемый контент

### ISSUE THREAD

**Issue by NobootRecord** [openvk/mobile-android-legacy#106]
**Телефон/ОС: Samsung Galaxy A6 2018/Android 10**\
**Разрешение экрана: 720×1480**

Добрый день! Установил сегодня свежую версию OpenVK Legacy из F-Droid.
Приложение работает весьма плавно и стабильно, но есть один серьёзный недочёт. Дело в том, что верхняя панель (с кнопкой меню и названием активного раздела) перекрывает контент таким образом, что он просто "обрезается". Как результат, я не могу целиком увидеть аватарку пользователя/сообщества и прочитать текст сообщения в самом верху раздела "Сообщения".
Как решение проблемы, предлагаю добавить автоматическое скрытие верхней панели при просмотре контента (и её появление при пролистывании вверх) либо просто прибить панель, чтобы под ней ничего не находилось...

С нетерпением жду решения проблемы. Заранее спасибо и удачи в разработке! 😉

![Screenshot_20230508-152740_OpenVK.jpg](https://user-images.githubusercontent.com/129325531/236830348-36889c2f-dda8-455c-b17e-e4689e81a773.jpg)

![Screenshot_20230508-154225_OpenVK.jpg](https://user-images.githubusercontent.com/129325531/236830368-46d2a784-e01a-44a4-aca0-b47c4c57f72f.jpg)

![Screenshot_20230508-154232_OpenVK.jpg](https://user-images.githubusercontent.com/129325531/236830391-3bea0869-f118-4458-b8a2-ff4da43f234c.jpg)

![Screenshot_20230508-154307_OpenVK.jpg](https://user-images.githubusercontent.com/129325531/236830406-87bf2441-414f-45ef-b774-c64cfa0796ba.jpg)

**Comment by tretdm** [comment]
Уточните, пожалуйста, версию приложения.

**Comment by NobootRecord** [comment]
Версия 1.1.182-beta
