### ISSUE TITLE
Зачем нужна открытая подпись приложения?

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#107]
Зачем то оставлен файл OpenVK KeyStore.jks и в build.gradle есть вот такой странный момент 
```
def_signing {
            storeFile file('OpenVK KeyStore.jks')
            keyAlias 'ovk_default_key'
            keyPassword 'Тут находится какой-то пароль'
            storePassword 'И тут'
        }
```
Только вот зачем это хранить в коде? Я так  понял это что-то используемое  для подписания приложения

**Comment by tretdm** [comment]
Открытая подпись теперь оставлена только для дебаг-сборок, а изначально был для раелизных.
