### ISSUE TITLE
Бесконечная загрузка после нажатия на кнопку входа на Android 3.2.1 планшет HTC Flyer

### ISSUE THREAD

**Issue by GAZON616** [openvk/mobile-android-legacy#108]
В чём собственно соль? Есть у меня планшет HTC Flyer с Android 3.2.1 Honeycomb и оболочкой Sense версии 1.1 которая была адаптированна для планшетов. Ну и пришла мне идея на него скачать OpenVK Legacy. Ввёл я почту потом пароль ну и нажал на кнопку входа. Но потом была тупо бесконечная загрузка. Пробовал я на доменах openvk.uk и openvk.su. Хотел попробовать уже openvk.co, но он даже с браузера не заходит, так как хостинг за этот домен судя по всему не оплачен. Также я пробовал две старые версии одна из которых модифицирована. Первым делом я опробовал версию 1.0.153-beta, но там после нажатия кнопки входа тупо вылет в главное меню. На старой модифицированной версии 1.0.161 в которой была заменена графика на оригинальную от ВК то же самое что в офф версии бесконечная загрузка (комм. разработчика - мод нарушает лицензию AGPLv3).

**Comment by GAZON616** [comment]
Ещё я откатил свой планшет до Android 2.3 там всё также.

**Comment by tretdm** [comment]
Воспользуйтесь на компьютере HTTPS-прокси в локальной сети, если уже активировано защищенное соединение и через него авторизация тупо не проходит (это можно проверить в настройках приложения > пункт "Настройки сети").

Cреди есть них [WebOne](https://github.com/ataueris/webone/releases) (обязательно нужен .NET Core Runtime.

**Comment by tretdm** [comment]
(естественное, настройки сети вступят только после перезагрузки приложения)
<img src="https://github.com/openvk/mobile-android-legacy/assets/76806170/a9ff47bd-5e9b-4758-9833-0618430c61c0" height="600"></img>      <img src="https://github.com/openvk/mobile-android-legacy/assets/76806170/7f1e9662-622e-4900-9ccd-1acad8b896bf" height="600"></img>
