### ISSUE TITLE
Сделать отдельную категории Emoji для флагов

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#115]
И я не пойму почему доступны всего несколько флагов, а файлах флагов много. Я заметил что флаги доступны с файла emoji_1f1e6_1f1e8.png по emoji_1f1ff_1f1fc.png

**Comment by tretdm** [comment]
Пожалуйста, смотрите ответ вот здесь: https://github.com/openvk/mobile-android-legacy/issues/109.
Этот issue не касается самого клиента, а адресуется только к библиотеке EmojiIcon.
