### ISSUE TITLE
Вечная загрузка информации о группе, выдаёт ошибку об отсутствии интернета при открытии списка друзей через свой профиль

### ISSUE THREAD

**Issue by ScratchApps** [openvk/mobile-android-legacy#12]
![Screenshot_20221019-193348](https://user-images.githubusercontent.com/103536027/196751777-61ba789f-91cc-47fe-ab28-06c1fe66b1ce.png)
![Screenshot_20221019-193438](https://user-images.githubusercontent.com/103536027/196751782-2b00060a-e59f-41ca-979d-a2b27ce359ea.png)

**Comment by tretdm** [comment]
ну так логично, барахлит у тебя инет

**Comment by ScratchApps** [comment]
> ну так логично, барахлит у тебя инет

И через вай-фай и через мобильный интернет. Посты группы загружаются полностью

**Comment by tretdm** [comment]
а логи можешь мне скинуть в лс: t.me/tretdm
как создать: "Настройки" > "Меню отладки" > "Запись логов в файл"
смотри не проморгай где логи хранятся

**Comment by ScratchApps** [comment]
> а логи можешь мне скинуть в лс: t.me/tretdm как создать: "Настройки" > "Меню отладки" > "Запись логов в файл" смотри не проморгай где логи хранятся

Отправил

**Comment by tretdm** [comment]
хотя у меня (и у других тоже) все прекрасно работает, поэтому фиксить я не вижу смысла. won't fix.
