### ISSUE TITLE
восстановление бекапа от Refresh вызывает странную проблему

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#121]
Надо создать бекап данных refresh и восстановить его в legacy, мы увидим экран авторизации, но не всё так просто на самом деле мы как бы авторизованы и если в О приложении нажать OpenVK Mobile, то можно вступить и вступится с аккаунта который был использован в рефреш

**Comment by tretdm** [comment]
Увы, но OpenVK Refresh развивается параллельно, как и Legacy. Поэтому ожидать чего-то такого, что могут подходить некоторые XML-файлы инстанции OpenVK Legacy вряд ли стоит по одной только причине - большая часть времени уделено на развитие OpenVK Legacy, а там и много чего переделано после выхода сборки №174, в т. ч. в системе аккаунтов.
