### ISSUE TITLE
Реализация просмотра аватарок пользователей и прикрепленных фотографий комментария

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#124]

**Comment by tretdm** [comment]
Насчет просмотра фотографий из окна "Запись на стене", где служит местом для комментариев к посту, ничего неизвестно, открывается просмотрщик как ни в чем не бывало.

https://github.com/openvk/mobile-android-legacy/assets/76806170/84faa7d9-1418-40dd-95bf-b85606c9fd19
