### ISSUE TITLE
Публикация поста "От имени сообщества"

### ISSUE THREAD

**Issue by lalka2016** [openvk/mobile-android-legacy#127]
Так же "Подпись автора"

**Comment by lalka2016** [comment]
![изображение](https://github.com/openvk/mobile-android-legacy/assets/99399973/ce25881b-0fed-41a1-8c40-3ea06da838be)

**Comment by tretdm** [comment]
👌

![изображение](https://github.com/openvk/mobile-android-legacy/assets/76806170/3fe5244d-e5ed-477a-8a08-ef1c188b487f)
