### ISSUE TITLE
Нестабильная работа приложения если флексить телефоном

### ISSUE THREAD

**Issue by Experience1-1** [openvk/mobile-android-legacy#13]
Заметил странное поведение приложения если вращать телефон/переходить в разделение экрана

1. Вылетает при попытке запустить в горизонтальной ориентации, но спокойно работает если запустить в вертикальной, а затем повернуть телефон
https://user-images.githubusercontent.com/104792484/196749993-4801d43e-8d3c-424b-b7a5-2a3863ebabab.mp4

2. В сплитскрине посты из ленты новостей немного залезают за края, даже в вертикальной ориентации, хотя например настройки, меню или посты в профиле отображаются корректно.
https://user-images.githubusercontent.com/104792484/196751351-7dc7d0d0-0bd3-4696-90a5-c250b91f37d5.mp4

3. При различных системных жестах (не только в сплитскрине) выбрасывает в новости и причем они грузятся по новой
https://user-images.githubusercontent.com/104792484/196752651-f37e06a9-d573-473b-94d6-fb3c034fbee0.mp4

3.1. даже промелькнул sample text moment
![image](https://user-images.githubusercontent.com/104792484/196752531-d4089dc3-c5ac-4df6-ad6c-d48c86f222e7.png)

**Comment by tretdm** [comment]
логи ко мне в личку: t.me/tretdm
"Настройки" > "Меню отладки" > "Запись логов в файл"

**Comment by tretdm** [comment]
фикс в [9298d6b](https://github.com/openvk/mobile-android-legacy/commit/9298d6b2f4d07998e6f8f6e1e0486c99ef27f7c4)
