### ISSUE TITLE
Прикрепление существующих фотографий к посту

### ISSUE THREAD

**Issue by lalka2016** [openvk/mobile-android-legacy#130]
Метод photos.getAll

**Comment by lalka2016** [comment]
![изображение](https://github.com/openvk/mobile-android-legacy/assets/99399973/d8663e3d-2b07-450a-bc48-88db5066af97)

**Comment by tretdm** [comment]
Ожидайте результат в issue #140, так как отсутствие этой фичи связано с отсутствием раздела "Фотографии" в приложении.
