### ISSUE TITLE
Сборка №123: при запуске приложения, аккаунт не выходит в онлайн

### ISSUE THREAD

**Issue by myslivets** [openvk/mobile-android-legacy#14]
При каждом запуске приложения нужно выбивать аккаунт в онлайн, сейчас же такое не происходит.
И вообще, желательно добавить это в настройки клиента, чтобы пользователь сам выбирал: быть видимым на сайте или же скрыть своё присутствие

**Comment by tretdm** [comment]
фикс в [9298d6b](https://github.com/openvk/mobile-android-legacy/commit/9298d6b2f4d07998e6f8f6e1e0486c99ef27f7c4)
