### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [openvk/mobile-android-legacy#147]
...because ffmpeg folders are gone... you moved them to experimental, right? https://github.com/openvk/mobile-android-legacy/commit/c0beb9c2927f0ff7802bfb0a4fa7e8b58ba18c75 & https://github.com/openvk/mobile-android-legacy/commit/90def03a199e80b24bf1f9cba17c3203e6418b6c & etc

So... why are your releases `app-prerelease-debug.apk ` containing `ffmpeg.so` then? The tag https://github.com/openvk/mobile-android-legacy/tree/1.1.208-beta has no ffmpeg :shrug: 

We should build from Tag w/o ffmpeg or a random commit from experimental or?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/cb38984c28cab95149742433552f01bfffc143b2

**Comment by tretdm** [comment]
yep, i moved to `experimental` branch and since I forgot to delete the generated `*.so` files, I will try to delete them and rebuild the APK again

**Comment by tretdm** [comment]
Okay, [check it](https://github.com/openvk/mobile-android-legacy/releases/tag/1.1.208-beta). I moved to `experimental` branch due to low experience in developing a video player based on two versions of `ffmpeg`. This is marked as experimental (unstable) feature.
