### ISSUE TITLE
Поддержка больше одной фотографии у постов

### ISSUE THREAD

**Issue by lalka2016** [openvk/mobile-android-legacy#151]
![изображение](https://github.com/openvk/mobile-android-legacy/assets/99399973/cd045d9b-ff92-4e05-8b87-d530a65b0acd)
![изображение](https://github.com/openvk/mobile-android-legacy/assets/99399973/b15b1ba1-c304-40e7-a547-86c2eff76b68)
(не грузится но думаю понятно)

**Comment by tretdm** [comment]
Перемещено в #140

**Comment by tretdm** [comment]
![Screenshot_20231201-212538423](https://github.com/openvk/mobile-android-legacy/assets/76806170/7e86df11-5374-4c41-ad7e-0102b096eafb)
Закончено в коммите https://github.com/openvk/mobile-android-legacy/commit/9094e5aa85a75f0fe24831e8fc121b8d811bd506
