### ISSUE TITLE
сборка №125: Не показывает количество друзей у пользователя

### ISSUE THREAD

**Issue by NikStepler** [openvk/mobile-android-legacy#16]
![photo_2022-10-20_11-45-54](https://user-images.githubusercontent.com/81332957/196901714-1b5d1515-7184-4d33-a4b1-d5497a5113c1.jpg)
![chrome_kxjY7zg4H7](https://user-images.githubusercontent.com/81332957/196901844-68de9821-1ece-4b9b-b4bf-af54e829f5f8.png)

**Comment by tretdm** [comment]
оно правда работает не всегда, конечно

**Comment by tretdm** [comment]
исправлено в коммите [e97abc3](https://github.com/openvk/mobile-android-legacy/commit/e97abc34c4c4756bd849eb718299178c80b2e394)
