### ISSUE TITLE
Вылет приложения при отсутствии личных аудиозаписей

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#160]
Даже не спрашивай как я это нашёл, если что аудиозаписей у меня не добавлено на аккаунт

**Comment by tretdm** [comment]
Но ты можешь вставить лог вылета прямо здесь из этого диалога или там логкэт не работает?

**Comment by tretdm** [comment]
![изображение](https://github.com/openvk/mobile-android-legacy/assets/76806170/c86d086c-fcd4-4385-bd19-33b4b0a7d7e1)

https://github.com/openvk/mobile-android-legacy/assets/76806170/01afefc3-88c0-455c-b75d-be18563961a6
