### ISSUE TITLE
Добавить поддержку Fastlane

### ISSUE THREAD

**Issue by WerySkok** [openvk/mobile-android-legacy#17]
Это необходимо для [добавления приложения ](https://gitlab.com/fdroid/rfp/-/issues/2237)в F-Droid.

**Comment by WerySkok** [comment]
@tretdm тут ещё спрашивают, не против ли ты добавления приложения. Напиши здесь (желательно на английском) своё согласие

**Comment by tretdm** [comment]
I personally don't mind publishing an OpenVK Legacy app on F-Droid.

**Comment by tretdm** [comment]
added fastlane metadata
