### ISSUE TITLE
Направление внешних ссылок из заметки (WebView) в браузер

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#172]

**Comment by tretdm** [comment]
Пояснительную бригаду, пожалуйста

**Comment by tretdm** [comment]
Внешние ссылки через WebView открывать нельзя, поэтому при нажатии при ссылку - ничего не отображается. Альтернативным вариантом может послужить открытие в браузере, но для этого нужно поработать над WebView, чтобы правильно направить ссылку.

![Screenshot_20240227-144548](https://github.com/openvk/mobile-android-legacy/assets/76806170/1539b714-9ec3-4f46-aa9d-bd29b39fb1d5)

**Comment by tretdm** [comment]
Полностью исправлено в https://github.com/openvk/mobile-android-legacy/commit/0f2a52831e262cc9ffe76e932e4efa6bc922ab00
