### ISSUE TITLE
`gradle-wrapper` upgrade issue

### ISSUE THREAD

**Issue by IzzySoft** [OpenVK/mobile-android-legacy#179]
there are 2 issues. First, your gradle-wrapper is misconfigured:

    distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

That's ancient, and the hash is missing in `gradle-wrapper.properties` as well. gradle is at 8.9 or higher already.

Next:

    classpath 'com.android.tools.build:gradle:2.3.2'

That's no longer available. It was on JCenter, which closed entirely a few weeks ago. Newer versions are available via Google's Maven.

Could you please fix these two issues? Thanks in advance!

**Comment by tretdm** [comment]
Hello, we are currently planning to resolve this issue.

I just tried to open this project in Android Studio, but there was an error due to outdated certificates for loading Gradle in the first place. And this affected almost all projects that were created in Android Studio 3.x and higher.

**Comment by tretdm** [comment]
JCenter has been replaced by MVN Repository, but the problems with missing dependencies are not being solved (https://github.com/OpenVK/mobile-android-legacy/commit/d59e5671566cc74ace9d9df866755bc9d06496e6), so the project will go into oblivion for some time, unfortunately, until we find one person who can provide a Maven repository with dependencies from the same JCenter.

**Comment by tretdm** [comment]
So, I agreed with Celestora that she will host the Maven repository.

Now requests for the AGP plugin are directed to https://mvnrepository.com/artifact, and those libraries that are not available in the Maven Central repository will be directed to https://maven.vriska.ru and https://maven.aliyun.com/repository/jcenter

**Comment by IzzySoft** [comment]
Sorry, opened a new one as I didn't see this here – which is already closed, but I still cannot build as there's no new release. Is there any ETA for a new release having these issues solved? It seems like the gradle wrapper is still the old one, unless that was worked on in a different branch.

**Comment by tretdm** [comment]
> First, your gradle-wrapper seems to be hopefully outdated. It still points to Gradle 4.2, which is ancient, and cannot even deal with Java 11 (it supports max JDK 8). Recent gradle versions start with an 8 (currently, 8.10.*). Could you please update that?

In general, the project was created on the basis of Android Studio versions that supported at least AGP 2.3.x, and it is unknown whether there is support for Java 8.

In any case, you can replace OpenVK Legacy with OpenVK Refresh for more convenient deployment on modern machines, but for this I need to transfer the API module of this application, which I have been delaying for so long due to my busy schedule.

**Comment by tretdm** [comment]
> Will you give us a ping when we shall check again?
We will give it through a separate issue in https://github.com/openvk/mobile-android-refresh. In any case, I'll come back to this.
