### ISSUE TITLE
билд 1.0.122-beta: Не даёт войти, дает неверный пароль или почту

### ISSUE THREAD

**Issue by SuperErnD** [openvk/mobile-android-legacy#18]
Это проблема скорее всего изза того что у меня знак `&` в пароле и  он не кодируется как-то (в js можно было бы это сделать через encodeURIComponent я не знаю как в яве)
фиксите
(я писал в дискорде вчера или послевчера)

**Comment by MatroCholo** [comment]
@SuperErnD Лол, & используется в апи. Кто разрешил использовать такие символы как часть пароля

**Comment by SuperErnD** [comment]
> @SuperErnD Лол, & используется в апи. Кто разрешил использовать такие символы как часть пароля

хз

**Comment by SuperErnD** [comment]
я логинюсь с таким паролем

все ок 📦

**Comment by SuperErnD** [comment]
на вебе конечно

**Comment by curoviyxru** [comment]
В этом нет никакой проблемы, просто нужно энкодить ссылку запроса API, как человек писал выше. В Java для этого присутствует URLEncoder.

**Comment by veselcraft** [comment]
> @SuperErnD Лол, & используется в апи. Кто разрешил использовать такие символы как часть пароля

Вообще пароли должны в кодировку URL форматироваться (типа %20%D3), разраб видимо этот момент просто пропустил

**Comment by SuperErnD** [comment]
да, я +- про это имею ввиду

**Comment by Andrmist** [comment]
сделал слишком сложный пароль для приложения :)
бамп, аналогичная проблема

**Comment by tretdm** [comment]
фикс в коммите [b78bb7f](https://github.com/openvk/mobile-android-legacy/commit/b78bb7fab61357e4bc6253b7934430e3214b5a89)

**Comment by tretdm** [comment]
добавлено в коммит [bfa47e7](https://github.com/openvk/mobile-android-legacy/commit/bfa47e7dfa704599a7b29134d622dec37e4018fa)
