### ISSUE TITLE
Снизилось качество кнопок и сплеша

### ISSUE THREAD

**Issue by Experience1-1** [openvk/mobile-android-legacy#19]
![Screenshot_20221020-150033_OpenVK](https://user-images.githubusercontent.com/104792484/196948962-4530f097-01d6-440f-a7dd-f26529788d2d.png)
![Screenshot_20221020-162920_OpenVK](https://user-images.githubusercontent.com/104792484/196948971-96902975-911a-45fb-852a-b6d80ab20382.png)

В предыдущих билдах
![Screenshot_20221019-205231_OpenVK](https://user-images.githubusercontent.com/104792484/196949091-fd3da1c2-6ffc-4e85-ae80-d2b3416cd26e.png)
![Screenshot_20221019-215404_OpenVK](https://user-images.githubusercontent.com/104792484/196949126-cc86102f-8a46-4a12-bc3c-ab9f7f487479.png)

Нужно приглядываться, но в реальности оч бросается в глаза
появилось вроде с 124 билда

**Comment by Experience1-1** [comment]
![Screenshot_20221020-163417_OpenVK](https://user-images.githubusercontent.com/104792484/196949907-fa0cecb3-7686-49c0-bb83-ac0185dc19c9.png)
вот ещё скрин, тут видно что иконка камеры более качественная чем пункты меню

**Comment by tretdm** [comment]
а зачем, если это легаси. уже говорили об этом.
