### ISSUE TITLE
Странный баг с процентами в опросах, с лайками и т.д.

### ISSUE THREAD

**Issue by tretdm** [openvk/mobile-android-legacy#24]
**В: Как воспроизводится баг?**
**О:** несколько раз проголосовать за один и тот же вариант.

**Comment by tretdm** [comment]
@tretdm опечатку допустил, когда думал "странная накрутка"

**Comment by tretdm** [comment]
апдейтед

**Comment by tretdm** [comment]
исправлено в коммите [e97abc3](https://github.com/openvk/mobile-android-legacy/commit/e97abc34c4c4756bd849eb718299178c80b2e394)

**Comment by tretdm** [comment]
хотя я видимо не все исправил, кек
![изображение](https://user-images.githubusercontent.com/76806170/197374083-77408508-be71-4dea-9787-7ed486262028.png)

**Comment by tretdm** [comment]
ибо свичи с отключалкой лайков сделал, но все равно каунтер на отрицательное количество идет

**Comment by R0ci0-V3rd3al** [comment]
hello. I'm glad this beautiful app came out... now I try to open "openvk" I have TCL android 6.0 on my phone and it doesn't open with a number I'm from Argentina... I already tried all the instances too, I don't use 2fa in my test account for vk

**Comment by tretdm** [comment]
> hello. I'm glad this beautiful app came out... now I try to open "openvk" I have TCL android 6.0 on my phone and it doesn't open with a number I'm from Argentina... I already tried all the instances too, I don't use 2fa in my test account for vk

firstly, you got to the wrong issue, and secondly, you only need to enter an email and password

**Comment by tretdm** [comment]
thirdly, OpenVK is not VK, but its free analogue. I advise you to register in openvk.uk

**Comment by Endedman** [comment]
@tretdm No, no. As @tretdm said, OpenVK is not a part of VK and it is not a proxy such as mpgram. It is another social net.
OpenVK can not get access to vk database

**Comment by tretdm** [comment]
@Endedman я тебе предлагаю референсить на новый issue, чтобы не засирать этот issue

**Comment by tretdm** [comment]
полностью пофиксил в [cfcbec3](https://github.com/openvk/mobile-android-legacy/commit/cfcbec327c76cc7b245465e7aa2cdf6c4fcc86a7)

**Comment by tretdm** [comment]
Там скорее всего больше 100% доходит при однократном нажатии, в остальных случаях уже исправил.

**Comment by tretdm** [comment]
либо парсер неправильно обрабатывает из API общее количество голосов, либо косяк в API. сложно сказать даже.

**Comment by tretdm** [comment]
![Screenshot_2022-10-24-08-03-49-789_uk openvk android legacy](https://user-images.githubusercontent.com/76806170/197428480-24e6fec2-1963-4f75-9905-3212c2a914f0.png)
вообще это редко происходит

**Comment by tretdm** [comment]
у меня никогда так не происходит, проценты более >100% не доходят случайным образом

**Comment by tretdm** [comment]
так еще раз открываю, похоже это еще не все

**Comment by tretdm** [comment]
В профиле аккаунта исправлено в коммите [e33d549](https://github.com/openvk/mobile-android-legacy/commit/e33d549a696c0852fb501188b82e04441e74c712). Finally!

**Comment by tretdm** [comment]
Еще не все, осталось решить баг, в котором все равно неправильно вычислялись проценты, если только один вариант набрал значительное количество голосов.
![изображение](https://user-images.githubusercontent.com/76806170/201863563-b347137a-82e1-43e5-8763-be2a7360e14c.png)

**Comment by tretdm** [comment]
Так, баг с лайками повторить не удалось, так как в моем случае клиент возвращает результат "кол-во лайков +1", но не "кол-во лайков +2", что ставит под сомнение возможность исправить этот баг.

С опросами постараюсь исправить.

**Comment by tretdm** [comment]
Уже все. И графику, и проценты в опросах полностью исправил, так что нареканий быть не должно и не будет.
