### ISSUE TITLE
Некорректная работа голосований 

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#25]
Если много раз нажать на пункт голосования, то он защитывает все нажатия. Из-за этого сходят с ума проценты.
![Screenshot_2022-10-22-13-21-17-676_uk openvk android legacy](https://user-images.githubusercontent.com/85897688/197334194-554cfc38-e4bb-402c-a8d4-7ef643ee7839.jpg)

**Comment by tretdm** [comment]
дубликат #24
