### ISSUE TITLE
Нет имени оригинала при пересылке поста себе в ленту

### ISSUE THREAD

**Issue by cfchnz** [openvk/mobile-android-legacy#27]
все на скриншоте![Screenshot_20221022_155642.jpg](https://user-images.githubusercontent.com/109415540/197340316-f2e7ec0a-3dd6-49ab-a300-8577b4de6c32.jpg)

**Comment by tretdm** [comment]
это апи

**Comment by veselcraft** [comment]
> это апи

так я ж пофиксил

**Comment by tretdm** [comment]
а ой

**Comment by tretdm** [comment]
я не увидел просто

**Comment by cfchnz** [comment]
ладно ![Screenshot_20221014_162956.png](https://user-images.githubusercontent.com/109415540/197345565-76b6563d-6df9-4b7e-9250-c0890add817d.png)

**Comment by tretdm** [comment]
В билде 140 постараюсь это сделать.

**Comment by tretdm** [comment]
а нет, я не стал эту фигню исправлять, так как я долгое время не мог понять как в вк4ме берется автор оригинале после репоста

**Comment by tretdm** [comment]
Уже неактуально. Баг уже исправлен.
