### ISSUE TITLE
Нет доступа к серверам

### ISSUE THREAD

**Issue by cfchnz** [openvk/mobile-android-legacy#29]
![Screenshot_20221022_212032_uk.openvk.android.legacy.jpg](https://user-images.githubusercontent.com/109415540/197356697-b452a8e0-78f1-46e9-bacc-31848e496104.jpg) интернет нормальный, ловит хорошо. скорее всего сервер пернул

**Comment by cfchnz** [comment]
![Screenshot_20221022_212220_uk.openvk.android.legacy.jpg](https://user-images.githubusercontent.com/109415540/197356729-de956069-fba6-4f42-a163-0fa2bb0a0f97.jpg)

**Comment by cfchnz** [comment]
такое чувство будто сервера овк сейчас выглядят именно так:

![IMG_20221022_212422_420.jpg](https://user-images.githubusercontent.com/109415540/197356833-4054da1f-e0d8-4c5d-a2b1-70d8c113461b.jpg)

**Comment by ayaaop** [comment]
Вы заходите с инстанса `openvk.co`?

**Comment by cfchnz** [comment]
угу

**Comment by tretdm** [comment]
вот этот скрин, который я удалил, ведет на телеграм-бота

**Comment by tretdm** [comment]
и вообще, нужно решать проблему с некорректными ответами с теми, кто пишет апи. например, @veselcraft
