### ISSUE TITLE
no work openvk.uk/reg 

### ISSUE THREAD

**Issue by R0ci0-V3rd3al** [openvk/mobile-android-legacy#30]
Hello ....I can't register...It says to use real names...What do I have to do to register on openvk.uk and use the app if it does not take me the registration?

**Comment by Endedman** [comment]
@R0ci0-V3rd3al You should go to openvk.uk/reg and enter data in all fields. Then go to the app and login with email and password you re typed.

**Comment by tretdm** [comment]
@R0ci0-V3rd3al create an issue in the [main repository](github.com/openvk/openvk) please. you are in the mobile app repository
