### ISSUE TITLE
Росстат прокрался в опросы (>100%)

### ISSUE THREAD

**Issue by SigmaTel71** [openvk/mobile-android-legacy#31]
Если проголосовать за вариант, за который голосуют все, случится абсолютно честный результат.
![Screenshot_20221024-024302.png](https://user-images.githubusercontent.com/17989678/197424079-9953ae79-72bd-44e9-aef1-915d974dcb6d.png)

**Comment by tretdm** [comment]
это какой билд стоит?

**Comment by SigmaTel71** [comment]
@tretdm , последний на текущий момент, 130.

**Comment by tretdm** [comment]
если у вас установлен билд <130, обновитесь и все. уже фикс есть.

**Comment by tretdm** [comment]
да, забыл сказл как это происходит: при однократном нажатии или несколько?

**Comment by tretdm** [comment]
чет вы не уточили, так как фикс я готовил для тех, кто голосует несколько раз

**Comment by SigmaTel71** [comment]
> да, забыл сказать как это происходит: при однократном нажатии или несколько?

Я нажал один раз на вариант ответа.

И да, по поводу обновления с прошлой версии на проверку валидности бага — этот скрин сделан именно что со 130-й сборки. После перезапуска приложения процент вернулся на нормальное значение.

**Comment by tretdm** [comment]
значит я где-то в общем количестве голосов накосячил, обычно это обрабатывается из API

**Comment by tretdm** [comment]
переоткрыл #24

**Comment by tretdm** [comment]
это вообще редко происходит, так что единственное, что я сделал: ставил лимит до 100%, чтобы это не смущало. а так won't fix
