### ISSUE TITLE
Нет реакции на физический Enter на экране авторизации

### ISSUE THREAD

**Issue by SigmaTel71** [openvk/mobile-android-legacy#32]
Если устройство оснащено физической клавиатурой или есть возможность подключения через USB-OTG, то нажатие Enter в поле ввода пароля не начнëт авторизацию после ввода всех учëтных данных.

**Comment by tretdm** [comment]
Реакция на физиечскую клавишу Enter добавлена в коммите [e33d549](https://github.com/openvk/mobile-android-legacy/commit/e33d549a696c0852fb501188b82e04441e74c712)
