### ISSUE TITLE
Нет постов в моём профиле

### ISSUE THREAD

**Issue by Experience1-1** [openvk/mobile-android-legacy#33]
В других профилях они есть 
![Screenshot_20221024-110312_OpenVK](https://user-images.githubusercontent.com/104792484/197467579-43a1711d-472a-4919-981f-a35ec37613c6.png)

(https://user-images.githubusercontent.com/104792484/197467482-47f95f92-7a69-4fb9-9d41-b49c2f15f22a.png)
![Screenshot_20221024-110513_OpenVK](https://user-images.githubusercontent.com/104792484/197467483-92d0b424-8f9b-45b4-8e77-525770d1d56d.png)
Но мои посты есть в ленте новостей
![Screenshot_20221024-110607_OpenVK](https://user-images.githubusercontent.com/104792484/197467489-b21ada71-993e-4f54-a2d7-a9cc65ac6215.png)

**Comment by tretdm** [comment]
@Experience1-1 тут прикол апи, я сделал так, чтобы вместо ошибки была стена пустая

**Comment by tretdm** [comment]
уже исправили
