### ISSUE TITLE
Аватарки не отображаются в разделе "Сообщения"

### ISSUE THREAD

**Issue by kosharigproekt** [openvk/mobile-android-legacy#38]
![Screenshot_20221101-174725_OpenVK](https://user-images.githubusercontent.com/110280681/199248552-058b46cd-d171-4482-937a-f4570ee7c9ef.jpg)

**Comment by veselcraft** [comment]
а скинь ещё раз как это в настоящем апи сделано

**Comment by tretdm** [comment]
Я уже скинул, Вова доделал, так что в следующем билде добавлю.

**Comment by tretdm** [comment]
добавлено в коммите [e33d549](https://github.com/openvk/mobile-android-legacy/commit/e33d549a696c0852fb501188b82e04441e74c712)
