### ISSUE TITLE
Не реализованы гиперссылки

### ISSUE THREAD

**Issue by ayaaop** [openvk/mobile-android-legacy#4]
![приложение](https://user-images.githubusercontent.com/58212796/196653218-b94e5301-c758-4a2b-8760-bdb065acb279.jpg)
![веб](https://user-images.githubusercontent.com/58212796/196653288-7d37a357-d980-47a2-acaf-2c1adccb63e9.jpg)

**Comment by tretdm** [comment]
Кстати, да. API, правда, недопилили до конца, чтобы нормальные гиперссылки поддерживать.

**Comment by ayaaop** [comment]
значит это не проблема самого приложения? закрывать?

**Comment by MatroCholo** [comment]
@ayaaop Вообще проблема
