### ISSUE TITLE
Количество лайков отображается по разному

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#42]
Значит заметил такую проблему у записи https://openvk.su/wall2287_1 в браузере и в приложение (В приложении нужно зайти в профиль Dmitry Tretyakov и пролистать в низ) разное количество лайков.
В приложении 3, а в браузере 2. А когда я в приложении снимаю лайк всё становится в норму и лайк остаётся один. А также если зайти в приложении в комментарии лайков становится 2

**Comment by tretdm** [comment]
дубликат #24 24
