### ISSUE TITLE
Имя и фамилия исчезает в комментариях

### ISSUE THREAD

**Issue by kosharigproekt** [openvk/mobile-android-legacy#45]
Когда отправляю коммент в какой то пост вместо моей имя и фамилии показывают null null
![Screenshot_20221105-174933_OpenVK](https://user-images.githubusercontent.com/110280681/200123192-e75c3a1e-db09-457d-847e-aa372bed37a0.jpg)

**Comment by tretdm** [comment]
вообще получение ID автора сделано паршиво, такую проблему наблюдаю в вк4ме
![Screenshot_20221105-210825](https://user-images.githubusercontent.com/76806170/200123907-41ba9c94-4d2a-44dc-986e-cd022b548338.png)

P.S. эти комментарии отправял точно не фрюлер.

**Comment by tretdm** [comment]
@kosharingproekt пока рано закрывать

**Comment by tretdm** [comment]
Пока с этим не сталкиваюсь. Возможно, это будет исправлено в последующих коммитах, если найдется такой баг в процессе тестирования, так как воспроизвести у меня не получилось.
