### ISSUE TITLE
Бесполезный интерфейс в профилях, странное отображение аватарок, шакальные аватарки у групп

### ISSUE THREAD

**Issue by cfchnz** [openvk/mobile-android-legacy#48]
все на видео
https://user-images.githubusercontent.com/109415540/200309821-1db223e7-9f5b-463e-89e4-4272bf8db333.mp4
https://user-images.githubusercontent.com/109415540/200309865-76a990cb-b5b0-46e1-8657-e2914b001d21.mp4

**Comment by cfchnz** [comment]
забыл добавить, тут еще неработающая информация группы, пропажа бокового меню при заходе в чужой профиль (не свой)

**Comment by tretdm** [comment]
это все чисто заглушки которые мне лень их убрать

**Comment by tretdm** [comment]
Закрыто по причине ненадобности в исправлении данной проблемы.
