### ISSUE TITLE
Удаление сообщений

### ISSUE THREAD

**Issue by AlesAlte** [openvk/mobile-android-legacy#5]
В LostVK есть поддержка удалений сообщений (чего нет даже в [OpenVK Web версии](https://openvk.uk))

Реализуйте это в OpenVK Legacy

**Comment by tretdm** [comment]
это будет в следующих билдах

**Comment by tretdm** [comment]
решил пока откладывать на следующие билды

**Comment by tretdm** [comment]
добавлено в коммите [9c8d64e](https://github.com/openvk/mobile-android-legacy/commit/9c8d64eb429089a0b40a6b3e2b75b4a180955982)
