### ISSUE TITLE
При переключении разделов лента не поднимается в самый верх

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#52]
Если я пролистаю в разделе "Подписки" вниз, потом переключусь на раздел "Все новости", то я буду на том же месте в ленте, что и в разделе подписок. (Смогу листнуть вверх)

https://user-images.githubusercontent.com/85897688/200803986-f907a057-268b-4e2e-baa2-fe4c21dcd6da.mp4

**Comment by tretdm** [comment]
добавлено в коммите [9c8d64e](https://github.com/openvk/mobile-android-legacy/commit/9c8d64eb429089a0b40a6b3e2b75b4a180955982)
