### ISSUE TITLE
Ограничение символов в окне об удалении.

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#53]
Если сообщение будет слишком длинным, оно полностью заполняет собой окно.

![Screenshot_2022-11-09-13-09-24-105_uk openvk android legacy](https://user-images.githubusercontent.com/85897688/200804242-53fe180b-6fb3-4ff3-82bb-211c5774225c.jpg)

**Comment by tretdm** [comment]
Будет установлен лимит на длину сообщения до 200 символов в этом диалоговом окне.

**Comment by tretdm** [comment]
добавлено в коммите [9c8d64e](https://github.com/openvk/mobile-android-legacy/commit/9c8d64eb429089a0b40a6b3e2b75b4a180955982)
