### ISSUE TITLE
Копирование сообщений.

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#54]
![IMG_20221109_132208_279](https://user-images.githubusercontent.com/85897688/200805235-afe49e52-afb2-476c-ba9f-95fdbbc5f95d.jpg)

**Comment by tretdm** [comment]
добавлено в коммите [9c8d64e](https://github.com/openvk/mobile-android-legacy/commit/9c8d64eb429089a0b40a6b3e2b75b4a180955982)
