### ISSUE TITLE
Спуск окна диалога вниз, после отправки сообщения.

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#55]
После отправки сообщения приходится самому пролистывать вниз, не то чтобы мне сложно, но с этой фичей будет выглядеть куда привычнее и красивее.

https://user-images.githubusercontent.com/85897688/200805957-b5bdccaf-a6db-45dd-929e-8c6b9d31e481.mp4

**Comment by tretdm** [comment]
добавлено в коммите [9c8d64e](https://github.com/openvk/mobile-android-legacy/commit/9c8d64eb429089a0b40a6b3e2b75b4a180955982)
