### ISSUE TITLE
Сокращение комментариев и репостов

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#56]
На инстансе есть посты с политическим спором, и под ним идёт комментарий на 3 километра, который абсолютно не сокращается.
![IMG_20221114_092003_185](https://user-images.githubusercontent.com/85897688/201589102-04a56021-03e7-4627-8daf-368e2426b195.jpg)

**Comment by tretdm** [comment]
В ленте новостей сокращение добавлено в репостах и комментариях. Это коммит [2fdf791](https://github.com/openvk/mobile-android-legacy/commit/2fdf7914ae81fa2f86940e344ace1c28b73fb8de).
Дальше - будут больше.

**Comment by tretdm** [comment]
Полноценное сокращение добавлено в [34bd49f](https://github.com/openvk/mobile-android-legacy/commit/34bd49fd32279c79efce71d3843a1ceac8f29e30). Теперь для сокращения учитывается не только длина поста, репоста или комментария в 500 символов, но и количество строк в 8.
