### ISSUE TITLE
Некорректное отображение спец-символов в окне просмотра комментариев

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#57]
Как должно быть:
![Screenshot_20221114-131900](https://user-images.githubusercontent.com/76806170/201589078-11457173-0acd-427b-ad05-1c10e76c2855.png)

Как есть:
![Screenshot_20221114-131904](https://user-images.githubusercontent.com/76806170/201589062-07dcaa8b-0992-4aec-a394-86e22c343942.png)

_комм @tretdm: я политоту убрал, извините._

**Comment by tretdm** [comment]
только вот по-хорошему надо будет убрать политоту, когда постишь скрины

**Comment by ZAZiOs** [comment]
> только вот по-хорошему надо будет убрать политоту, когда постишь скрины

И то верно, но отредачить скрины было негде. Ща в телеге тогда сделаю и попробую заменить

**Comment by tretdm** [comment]
я сам это сделаю, не нужно

**Comment by ZAZiOs** [comment]
> я сам это сделаю, не нужно

Да я уже всё

**Comment by tretdm** [comment]
Исправлено в коммите [2fdf791](https://github.com/openvk/mobile-android-legacy/commit/2fdf7914ae81fa2f86940e344ace1c28b73fb8de)
