### ISSUE TITLE
pre-release changelogs are missing

### ISSUE THREAD

**Issue by IzzySoft** [openvk/mobile-android-legacy#59]
Since `versionCode: 143` there were no new [per-release changelogs](https://github.com/openvk/mobile-android-legacy/tree/main/fastlane/metadata/android/en-US/changelogs) added to fastlane. Will you pick up again adding them (with the next release, no need to fill the gap), or shall I drop pulling them?

**Comment by tretdm** [comment]
ok, later

**Comment by tretdm** [comment]
Added in [e2348ae](https://github.com/openvk/mobile-android-legacy/commit/e2348ae58fe92a148450db9ddcdfab1ea31e3930).

**Comment by IzzySoft** [comment]
Thanks! And it is is indeed PER release changelogs (one file per release), not PRE release changelogs (notes on pre-releases) :wink: Please keep adding them with future releases :star_struck:
