### ISSUE TITLE
Нельзя приближать картинки

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#6]
Вот тут мемес смешной очень, а я не могу понять что там написано. 
![IMG_20221019_132657_731](https://user-images.githubusercontent.com/85897688/196666659-893308b4-23d8-4eab-b044-482a5ffa6d48.jpg)
Приближения нет.

**Comment by Experience1-1** [comment]
да походу тут предпросмотр впринципе отсутствует
мои предположения: либо он работает очень криво, либо его не было даже в оригинале

**Comment by tretdm** [comment]
в оригинале-то оно было, просто зумирования нету. надо бы реализовать смену качества картинки, так как там чисто gif вместо jpg

**Comment by tretdm** [comment]
добавлено в коммите [a2b2a21](https://github.com/openvk/mobile-android-legacy/commit/a2b2a2140d0d445f7068eba0a26e0c1d53be3365)
