### ISSUE TITLE
Проёб в украинской локали

### ISSUE THREAD

**Issue by veselcraft** [openvk/mobile-android-legacy#67]
![image](https://user-images.githubusercontent.com/22993408/206927221-f85332b6-8aea-4f6e-9da6-30cea69dcbb1.png)

# пояснялка 
Лимонадный киоск, [11.12.2022 23:28]
"передплата" это когда ты бабки за что-то платишь

Лимонадный киоск, [11.12.2022 23:29]
а в данном случае "підписки"

Лимонадный киоск, [11.12.2022 23:29]
под письки

**Comment by tretdm** [comment]
0a74fb1
