### ISSUE TITLE
Рекурсивный переход в профиль

### ISSUE THREAD

**Issue by SigmaTel71** [openvk/mobile-android-legacy#7]
Если на публикации любого пользователя на стене нажать на троеточие, которое должно (по идее) открыть меню, то приложение ещё раз откроет профиль пользователя. Количество вложенных действий такого рода не ограничено.

**Comment by SigmaTel71** [comment]
@ayaaop, а можно просто было не показывать кнопку. 🤷🏻‍♂️

**Comment by tretdm** [comment]
[37ebe0b](https://github.com/openvk/mobile-android-legacy/commit/37ebe0be8ba695376a1d0daf6b9c9db13716983e)
