### ISSUE TITLE
Не отображаются более 20 комментариев под постом

### ISSUE THREAD

**Issue by NikStepler** [openvk/mobile-android-legacy#8]
При попытке оставить комментарий под записью он сначала оставляет его под null null, если перезайти на пост комментарий пропадает
![photo_2022-10-19_14-30-54 (2)](https://user-images.githubusercontent.com/81332957/196679578-60b42531-9cc2-4e03-98dd-10924f9991c9.jpg)

**Comment by tretdm** [comment]
![изображение](https://user-images.githubusercontent.com/76806170/196719490-3cdd76ca-c4dd-4e7b-a861-9b0d8ebc0528.png)
Так подожди, я же выставил количество в 50 комментариев. Почему тут более 20 не показывает? Очень странно

**Comment by tretdm** [comment]
![изображение](https://user-images.githubusercontent.com/76806170/196744612-d7a2e8b8-055e-4da2-997f-470af90f1960.png)
я понял в чем проблема

**Comment by tretdm** [comment]
[37ebe0b](https://github.com/openvk/mobile-android-legacy/commit/37ebe0be8ba695376a1d0daf6b9c9db13716983e)
