### ISSUE TITLE
Ссылка на аккаунт в ответе не работает

### ISSUE THREAD

**Issue by ZAZiOs** [openvk/mobile-android-legacy#9]
![IMG_20221019_161939](https://user-images.githubusercontent.com/85897688/196720365-e9faff96-c105-40a9-844a-4b8f0b3ca168.jpg)
![IMG_20221019_172931_700](https://user-images.githubusercontent.com/85897688/196720377-b248d61f-dfd1-45d6-bac8-d98c83ac5c83.jpg)

**Comment by tretdm** [comment]
это проблема самого апи

**Comment by AlesAlte** [comment]
#4

**Comment by tretdm** [comment]
а стоп, это комменты. я извиняюсь

**Comment by tretdm** [comment]
короче я пытался с ньюсфидом сделать, но апи косячит все равно. надо чтоб альтернативные скриннеймы возвращал. а что с комментариями - это оставлю на потом

**Comment by tretdm** [comment]
фикс в [9298d6b](https://github.com/openvk/mobile-android-legacy/commit/9298d6b2f4d07998e6f8f6e1e0486c99ef27f7c4)
