### ISSUE TITLE
Открытие группы/профиля только с уже запущенного приложения

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-legacy#97]
У меня два клиента OpenVK и если попытаться открыть группу через меню группы, зачем-то спрашивает открыть через какой клиент открыть

**Comment by tretdm** [comment]
Доделано в [c84fdbe](https://github.com/openvk/mobile-android-legacy/commit/c84fdbe2631b2117f5f5c373f84fb0cc3893d611)

**Comment by tretdm** [comment]
Отмена, видимо, данный фикс не сработал.

**Comment by tretdm** [comment]
а лол, у меня фикса нет, видимо до этого коммита я отменил те изменения с открытиями групп, которые там были

**Comment by tretdm** [comment]
А нет, тогда че за херня? Вроде как сообщает пакетному менеджеру, что нужно открыть только в уже запущенном приложении, а на деле все равно открывается диалог выбора приложения?

![изображение](https://user-images.githubusercontent.com/76806170/235432133-8430d923-57ff-4408-a720-e03cf366bf1b.png)

**Comment by tretdm** [comment]
А, как оказалось, намного сделать именно вот так.
![studio64_CqppYSVZf3](https://user-images.githubusercontent.com/76806170/235432743-3357c89d-3b9d-4675-a68a-95e1a9d58149.png)
